# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LexguardAgent < Formula
  desc "LexGuard agent — React for DevOps"
  homepage "https://lexguard.app"
  version "0.0.27"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://cdn.lexguard.app/releases/agent/0.0.27/lexguard-agent-0.0.27-darwin-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "7c4af2788d951abb437849f2ec22132dd2c9f7ef81442f6eaf9457ddfb47f544"

      define_method(:install) do
        bin.install "lexguard-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://cdn.lexguard.app/releases/agent/0.0.27/lexguard-agent-0.0.27-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "65243b5b4f00884be3497d2a7ac6d5a221c9246640a85d7af8ba71c0a46713ff"

      define_method(:install) do
        bin.install "lexguard-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://cdn.lexguard.app/releases/agent/0.0.27/lexguard-agent-0.0.27-linux-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "3bb9fbe155455ebbaa3911f94b160596c823d9a4dd3ac96a21a8d14fdd546586"
      define_method(:install) do
        bin.install "lexguard-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://cdn.lexguard.app/releases/agent/0.0.27/lexguard-agent-0.0.27-linux-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "5276d860ad5b9aaa8a0493c764537699d05bfa09dfc251a2ecbeb7d395ab4f8f"
      define_method(:install) do
        bin.install "lexguard-agent"
      end
    end
  end

  def caveats
    <<~EOS
      Configure the agent with the command shown in your LexGuard portal:
        lexguard-agent config set addr <host>/api/infrastructure/agent/<group_id>

      Then start it as a background service:
        brew services start lexguard-agent

      The CLI and the brew service both read/write
        #{HOMEBREW_PREFIX}/var/lexguard-agent/settings.json
      so the token persisted by `config set` is the same one launchd uses.

      View or change config later:
        lexguard-agent config show
        lexguard-agent config path
    EOS
  end

  service do
    run [opt_bin/"lexguard-agent", "--production", "--log-file=false"]
    keep_alive true
    environment_variables LEXGUARD_CONFIG_DIR: (var/"lexguard-agent").to_s
    log_path var/"log/lexguard-agent.log"
    error_log_path var/"log/lexguard-agent.err.log"
    working_dir var/"lexguard-agent"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lexguard-agent --version")
  end
end
