# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LexguardAgent < Formula
  desc "LexGuard agent — React for DevOps"
  homepage "https://lexguard.app"
  version "0.0.3"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://cdn.lexguard.app/releases/agent/0.0.3/lexguard-agent-0.0.3-darwin-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "20f2ec02394b23b0fff80bf431e9872df06526fcb3b98e6abe04949aeb922c20"

      define_method(:install) do
        bin.install "lexguard-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://cdn.lexguard.app/releases/agent/0.0.3/lexguard-agent-0.0.3-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "ea5e9b7c7da56b228ac74d4b74ea85335f9071e7e480359da08dba2167912f39"

      define_method(:install) do
        bin.install "lexguard-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://cdn.lexguard.app/releases/agent/0.0.3/lexguard-agent-0.0.3-linux-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "f920c6c0914e07a9e38305851ba03f89590a4192fa3880be2aadeb71c90b3e52"
      define_method(:install) do
        bin.install "lexguard-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://cdn.lexguard.app/releases/agent/0.0.3/lexguard-agent-0.0.3-linux-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "23f91379c427bfca33776bad5a204fb895be475bf38fe6a3ed7e262a8ac6264e"
      define_method(:install) do
        bin.install "lexguard-agent"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lexguard-agent --version")
  end
end
