# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LexguardAgent < Formula
  desc "LexGuard agent — React for DevOps"
  homepage "https://lexguard.app"
  version "0.0.6"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://cdn.lexguard.app/releases/agent/0.0.6/lexguard-agent-0.0.6-darwin-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "30df43dd28cfe41159de394e510fc4ca903b894a0c45b758d2f3db351e73281c"

      define_method(:install) do
        bin.install "lexguard-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://cdn.lexguard.app/releases/agent/0.0.6/lexguard-agent-0.0.6-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "21af061aeae8d002ca3b575e262d63e35e1917dbb215d47fe9f10ef9db0533f8"

      define_method(:install) do
        bin.install "lexguard-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://cdn.lexguard.app/releases/agent/0.0.6/lexguard-agent-0.0.6-linux-amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "daa0cbd0ba6f697f705560207ed50ccd245efe81991489773050ed3620037d8d"
      define_method(:install) do
        bin.install "lexguard-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://cdn.lexguard.app/releases/agent/0.0.6/lexguard-agent-0.0.6-linux-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "2c932dac7cb0e70542cf9f625d79dccb23ba4f4b321af18733f593dd35978485"
      define_method(:install) do
        bin.install "lexguard-agent"
      end
    end
  end

  def caveats
    <<~EOS
      Configure the agent with the command shown in your LexGuard portal:
        lexguard-agent config set addr <host>/api/infrastructure/agent/<group_id>

      Then start it as a background service:
        brew services start lexguard-agent

      View or change config later:
        lexguard-agent config show
        lexguard-agent config path
    EOS
  end

  service do
    run [opt_bin/"lexguard-agent", "--production", "--log-file=false"]
    keep_alive true
    log_path var/"log/lexguard-agent.log"
    error_log_path var/"log/lexguard-agent.err.log"
    working_dir var/"lexguard-agent"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lexguard-agent --version")
  end
end
